/* miniwin_user.c generated by MiniWin code generator. */

#include <stdlib.h>
#include "miniwin.h"
#include "miniwin_user.h"
#include "window_camera.h"


mw_handle_t window_window_camera_handle;




void mw_user_root_paint_function(const mw_gl_draw_info_t *draw_info)
{
    mw_gl_set_solid_fill_colour(MW_HAL_LCD_PURPLE);
    mw_gl_clear_pattern();
    mw_gl_set_border(MW_GL_BORDER_OFF);
    mw_gl_set_fill(MW_GL_FILL);
    mw_gl_rectangle(draw_info, 0, 0, MW_ROOT_WIDTH, MW_ROOT_HEIGHT);
}

void mw_user_root_message_function(const mw_message_t *message)
{
    (void)message;
}

void mw_user_init(void)
{
    mw_util_rect_t r;

    mw_util_set_rect(&r, 10, 15, 162, 139);
    window_window_camera_handle = mw_add_window(&r,
        "Camera", 
        window_window_camera_paint_function,
        window_window_camera_message_function,
        NULL,
        0U,
        0U | MW_WINDOW_FLAG_HAS_BORDER | MW_WINDOW_FLAG_HAS_TITLE_BAR | MW_WINDOW_FLAG_IS_VISIBLE,
        NULL);

    mw_paint_all();
}
