/* window_camera.h generated by MiniWin code generator. */

#ifndef WINDOW_window_camera_H
#define WINDOW_window_camera_H

#ifdef __cplusplus
 extern "C" {
#endif

#include "miniwin.h"

/**
 * Window paint routine, called by window manager.
 *
 * @param window_handle The window identifier in the array of windows
 * @param draw_info Draw info structure describing offset and clip region
 * @note Do not call this directly from user code
 */
void window_window_camera_paint_function(mw_handle_t window_handle, const mw_gl_draw_info_t *draw_info);

/**
 * Window message handler called by the window manager.
 *
 * @param message The message to be processed
 * @note Do not call this directly from user code
 */
void window_window_camera_message_function(const mw_message_t *message);

#ifdef __cplusplus
}
#endif

#endif
